export const AllCoursesList = [
  {
    id: 1,
    title: "Complete Web Development Course",
    category: "Development",
    instructor: "John Doe",
    duration: "12h 30m",
    students: 1200,
    price: "$49",
    image: "/images/course1.jpeg",
  },
  {
    id: 2,
    title: "Mastering Photoshop for Beginners",
    category: "Art & Design",
    instructor: "Jane Smith",
    duration: "8h 15m",
    students: 980,
    price: "Free",
    image: "/images/course2.jpg",
  },
  {
    id: 3,
    title: "Digital Marketing Essentials (Intermediate)",
    category: "Business",
    instructor: "Alice Johnson",
    duration: "10h 45m",
    students: 650,
    price: "$39",
    image: "/images/course3.jpg",
  },
  {
    id: 4,
    title: "Freelancing Online for Beginners",
    category: "Tech",
    instructor: "Michael Lee",
    duration: "6h 20m",
    students: 430,
    price: "$29",
    image: "/images/course4.jpg",
  },
  {
    id: 5,
    title: "UI/UX Design Fundamentals",
    category: "Design",
    instructor: "Emily Carter",
    duration: "9h 10m",
    students: 720,
    price: "$35",
    image: "/images/course5.png",
  },
  {
    id: 6,
    title: "React.js From Zero to Hero",
    category: "Development",
    instructor: "Daniel Brown",
    duration: "14h 50m",
    students: 1500,
    price: "$59",
    image: "/images/course6.jpg",
  },
  {
    id: 7,
    title: "Data Analysis with Excel & Power BI",
    category: "Data",
    instructor: "Sophia Wilson",
    duration: "11h 40m",
    students: 890,
    price: "$45",
    image: "/images/course7.jpg",
  },
  {
    id: 8,
    title: "Personal Branding & LinkedIn Growth",
    category: "Business",
    instructor: "Robert King",
    duration: "5h 30m",
    students: 560,
    price: "Free",
    image: "/images/course8.jpg",
  },
];
